### ISSUE TITLE
Foliage Menu reverting to "off"

### ISSUE THREAD

**Issue by adam-mock** [scfmod/FS22_advancedGameplaySettings#4]
Hello and thanks for your mod! I have an issue where the settings in the foliage menu do not save. I'll turn the settings on and then exiting the menu or switching to another tab and back they again appear to be off. If I turn the settings on and then attempt to place foliage I get the "land not owned" message.

**Comment by scfmod** [comment]
Somehow I forgot to update some name values in the GUI. Fixed now, thanks for reporting! :-)

**Comment by adam-mock** [comment]
Amazing, thank you!
